### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by gabestev** [jmreyes/passport-google-id-token#23]
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

I got this when installing, can you help update it?

**Comment by jmreyes** [comment]
Hi, it should be solved in the latest release (0.4.3), thank you!
